### ISSUE TITLE
Connect to heat-pump

### ISSUE THREAD

**Issue by dala318** [dala318/esphome-rego600#1]
I have yet no working HW to test this integration. 
Anyone interested, feel free to try it out.
Recommend starting with a sensor that is read-only

**Comment by atliant** [comment]
Hi @dala318, intresting project!
I have a Rego 600 and an ESP32 board but I'm not sure how to wire them together. 
Can you give me some hints on how to do it? I'd be happy to try it out.

Thanks

**Comment by dala318** [comment]
Hi. Have a look at issue #5 where some issues in this topic is discussed.
My own attempt was to just put a bi-directional TTL logic level converter between the ESP32 and Rego600 but I'm having issues getting communication working.

https://www.sparkfun.com/products/12009

**Comment by dala318** [comment]
As I do have a https://husdata.se/produkt/h66-wifi-gateway/ that works I'm interested to flash an ESPHome firmware on it to rule out HW issues but I'm afraid I won't be able to backup it properly before to have the option to go back to the legacy firmware later on.

**Comment by S4ube** [comment]
Here is some interesting discussion connection between rego600 and ESP32: https://forum.arduino.cc/t/serial-communication-via-optocouplers/686872/26

**Comment by dala318** [comment]
With setup according to https://forum.arduino.cc/t/serial-communication-via-optocouplers/686872/25 it's actually working to read a sensor and binary sensor, see #5
